name: CI/CD Pipeline (Docker + Terraform)

on:
  push:
    branches:
      - main

jobs:
  # 1. ПЕРЕВІРКА КОДУ
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: Run htmlhint on HTML files
        run: htmlhint index.html

  # 2. ЗБІРКА І ВІДПРАВКА НА DOCKER HUB
  build-and-push:
    needs: lint # Чекає на успішний lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lab4:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/lab4:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout

  # 3. РОЗГОРТАННЯ ІНФРАСТРУКТУРИ ЧЕРЕЗ TERRAFORM
  terraform-deploy:
    needs: build-and-push # Чекає, поки Докер образ точно опиниться на Хабі
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Твій регіон (Стокгольм)

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
